// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OAuthDoZero.Server.Data;

#nullable disable

namespace OAuthDoZero.Server.Data.Migrations
{
    [DbContext(typeof(OAuthDbContext))]
    [Migration("20260221190917_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OAuthDoZero.Server.Models.AccessToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Audience")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Claims")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("JwtId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TokenId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsRevoked");

                    b.HasIndex("JwtId");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "ClientId");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.AuthorizationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CodeChallenge")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CodeChallengeMethod")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nonce")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RequestedClaims")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("State")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Code");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsUsed");

                    b.HasIndex("UserId", "ClientId");

                    b.ToTable("AuthorizationCodes");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("AccessTokenLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("AllowPlainTextPkce")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowRefreshToken")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AllowedScopes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AuthorizationCodeLifetime")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ClientType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GrantTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUris")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshTokenLifetime")
                        .HasColumnType("int");

                    b.Property<bool>("RequirePkce")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResponseTypes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ClientId");

                    b.HasIndex("IsActive");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = "demo-spa",
                            AccessTokenLifetime = 3600,
                            AllowPlainTextPkce = false,
                            AllowRefreshToken = true,
                            AllowedScopes = "openid profile email offline_access",
                            AuthorizationCodeLifetime = 300,
                            ClientName = "Aplicação Demo SPA",
                            ClientSecret = "$2a$12$1ePlOPG5M8N7X7K8M7K8MeHw...",
                            ClientType = "public",
                            CreatedAt = new DateTime(2026, 2, 21, 19, 9, 17, 391, DateTimeKind.Utc).AddTicks(900),
                            Description = "Aplicação de demonstração Single Page App",
                            GrantTypes = "authorization_code",
                            IsActive = true,
                            PostLogoutRedirectUris = "http://localhost:3000,https://localhost:3000",
                            RedirectUris = "http://localhost:3000/callback,https://localhost:3000/callback",
                            RefreshTokenLifetime = 2592000,
                            RequirePkce = true,
                            ResponseTypes = "code"
                        });
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.RefreshToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AccessTokenId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Scopes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("TokenId");

                    b.HasIndex("AccessTokenId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash");

                    b.HasIndex("IsUsed", "IsRevoked");

                    b.HasIndex("UserId", "ClientId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.Scope", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AssociatedClaims")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Emphasize")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Required")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ShowInConsentScreen")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Name");

                    b.HasIndex("IsActive");

                    b.ToTable("Scopes");

                    b.HasData(
                        new
                        {
                            Name = "openid",
                            AssociatedClaims = "[\"sub\"]",
                            CreatedAt = new DateTime(2026, 2, 21, 19, 9, 17, 391, DateTimeKind.Utc).AddTicks(769),
                            Description = "Permite autenticação usando OpenID Connect",
                            DisplayName = "OpenID",
                            Emphasize = false,
                            IsActive = true,
                            Required = true,
                            ShowInConsentScreen = false,
                            Type = "identity"
                        },
                        new
                        {
                            Name = "profile",
                            AssociatedClaims = "[\"name\", \"given_name\", \"family_name\", \"preferred_username\", \"picture\", \"website\", \"gender\", \"birthdate\", \"zoneinfo\", \"locale\", \"updated_at\"]",
                            CreatedAt = new DateTime(2026, 2, 21, 19, 9, 17, 391, DateTimeKind.Utc).AddTicks(774),
                            Description = "Acesso às informações do seu perfil",
                            DisplayName = "Perfil",
                            Emphasize = false,
                            IsActive = true,
                            Required = false,
                            ShowInConsentScreen = true,
                            Type = "identity"
                        },
                        new
                        {
                            Name = "email",
                            AssociatedClaims = "[\"email\", \"email_verified\"]",
                            CreatedAt = new DateTime(2026, 2, 21, 19, 9, 17, 391, DateTimeKind.Utc).AddTicks(775),
                            Description = "Acesso ao seu endereço de email",
                            DisplayName = "Email",
                            Emphasize = true,
                            IsActive = true,
                            Required = false,
                            ShowInConsentScreen = true,
                            Type = "identity"
                        },
                        new
                        {
                            Name = "offline_access",
                            CreatedAt = new DateTime(2026, 2, 21, 19, 9, 17, 391, DateTimeKind.Utc).AddTicks(777),
                            Description = "Permite acesso às suas informações mesmo quando você estiver offline",
                            DisplayName = "Acesso offline",
                            Emphasize = true,
                            IsActive = true,
                            Required = false,
                            ShowInConsentScreen = true,
                            Type = "resource"
                        });
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Picture")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PreferredUsername")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.AccessToken", b =>
                {
                    b.HasOne("OAuthDoZero.Server.Models.Client", "Client")
                        .WithMany("AccessTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthDoZero.Server.Models.User", "User")
                        .WithMany("AccessTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.AuthorizationCode", b =>
                {
                    b.HasOne("OAuthDoZero.Server.Models.Client", "Client")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthDoZero.Server.Models.User", "User")
                        .WithMany("AuthorizationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.RefreshToken", b =>
                {
                    b.HasOne("OAuthDoZero.Server.Models.AccessToken", "AccessToken")
                        .WithOne("RefreshToken")
                        .HasForeignKey("OAuthDoZero.Server.Models.RefreshToken", "AccessTokenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OAuthDoZero.Server.Models.Client", "Client")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OAuthDoZero.Server.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessToken");

                    b.Navigation("Client");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.AccessToken", b =>
                {
                    b.Navigation("RefreshToken");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.Client", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("AuthorizationCodes");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("OAuthDoZero.Server.Models.User", b =>
                {
                    b.Navigation("AccessTokens");

                    b.Navigation("AuthorizationCodes");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
